version: '3.4'

services:
  bankappbackend:
    image: ${DOCKER_REGISTRY-}bankappbackend
    build:
      context: .
      dockerfile: BankAppBackend/Dockerfile
    depends_on:
      - redis-bank
      - sql

  bank-app-frontend:
    image: ${DOCKER_REGISTRY-}bankappfrontend
    build:
      context: .
      dockerfile: bank-app-frontend/Dockerfile

  sql:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  redis-bank:
    image: redis:latest
    ports:
      - "6379:6379"
